import { Inter } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import ProductCard from "../components/Product/productCard";
import DetailsCard from "../components/Product/detailsCard";
import SliderCard from "../components/Product/sliderProduct";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [pokemonList, setpokemonList] = useState<any>([]);

  const gqlQuery = `query pokemons($limit: Int, $offset: Int) {
    pokemons(limit: $limit, offset: $offset) {
      results {
        url
        name
        image
      },
    }
  }`;

  const gqlVariables = {
    limit: 10,
    offset: 1,
  };
  useEffect(() => {
    const res = async () => {
      try {
        const res = await fetch("https://graphql-pokeapi.graphcdn.app/", {
          credentials: "omit",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            query: gqlQuery,
            variables: gqlVariables,
          }),
          method: "POST",
        }).then((res) => res.json());
        setpokemonList(res?.data?.pokemons?.results);
      } catch (error) {}
    };
    res();
  }, []);

  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.main1}>
          <div className="flex justify-center mb-5">
            <Image
              src={"/assets/images/Logo.png"}
              alt="logo"
              width={200}
              height={200}
            />
          </div>
          <div className={styles.productView}>
            <ProductCard arr={pokemonList} />
          </div>

          <div className={styles.sliderView}>
            <SliderCard arr={pokemonList} />
          </div>
        </div>
      </div>
      <div className={styles.detailsView}>
        <DetailsCard />
      </div>
      <div>
        <div className={` bg-white  ${styles.main2}`}>
          <div className="relative">
            <div className="flex justify-center w-[350px] h-[100px] mx-auto">
              <Image
                className=""
                src={"/assets/images/Brush.png"}
                alt="logo"
                fill
              />
            </div>
            <p className="text-center text-[40px] text-blue-900 absolute font-bold xs:text-[30px] top-0">
              Ash & Pikachu Arrive in Pokemon Universe
            </p>
          </div>

          {/* <div className=" grid grid-cols-12 gap-3">
            <div className="col-span-7">
              <div className="flex justify-between">
                <div className="w-[700px]">
                  <span className="text-justify w-[500px] font-semibold">
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                    Incidunt reprehenderit nesciunt amet perferendis pariatur
                    qui culpa error, ducimus modi, commodi facilis delectus
                    earum a mollitia quae blanditiis deserunt deleniti minima,
                    id aut expedita molestias tempore? Cum eos facilis nisi non!
                  </span>
                  <div className="flex py-2">
                    <span className="text-justify w-[500px] font-semibold">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Neque labore placeat unde nesciunt repellat, animi iusto
                      dolores reiciendis, earum, doloremque debitis dolor
                      aspernatur. Quo deserunt corrupti, nesciunt quis quod modi
                      aliquam mollitia consectetur. Atque eaque sapiente, illum
                      molestias expedita dolore omnis culpa impedit architecto
                      nemo fuga expedita dolore omnis culpa impedit architecto
                      nemo fuga expedita dolore omnis culpa impedit architecto
                      nemo fuga
                    </span>
                    <div className="px-2">
                      <Image
                        src={"/assets/images/Image04.png"}
                        alt="Image04"
                        width={200}
                        height={250}
                      />
                    </div>
                  </div>

                  <p className="text-justify  py-2 font-semibold">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                    Eveniet voluptatum modi quia reiciendis quae fuga, alias
                    iusto cupiditate fugit laboriosam dolore velit atque tenetur
                    adipisci voluptate eum voluptates quisquam recusandae. Animi
                    dolor hic labore fugit sequi consequatur minima accusamus
                    odit amet ipsa aliquid error commodi aliquam, asperiores
                    perspiciatis velit. Repellendus non sunt, deleniti rerum aut
                    officiis nisi! Error culpa consectetur non explicabo, nisi
                    corrupti reiciendis accusantium amet nulla voluptatibus
                    voluptatum?
                  </p>
                </div>
                <div className="p-3">
                  <Image
                    src={"/assets/images/Image03.png"}
                    alt="Image05"
                    width={200}
                    height={250}
                  />
                  <Image
                    className="py-3 mt-3"
                    src={"/assets/images/Image02.png"}
                    alt="Image05"
                    width={200}
                    height={300}
                  />
                </div>
              </div>
              <p className="text-justify py-2 font-semibold">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores
                eveniet asperiores molestiae, aliquid explicabo consequuntur
                totam tempora perspiciatis minus quibusdam, commodi harum
                voluptatum eum tempore illo praesentium? Aliquid minima
                perferendis cupiditate, ipsum ipsa tempora nemo corporis modi
                labore explicabo molestiae ex at nisi, similique suscipit dolor
                culpa dolore voluptates sint recusandae?
                <br /> Nisi animi voluptate nesciunt quidem quas, ipsum harum,
                commodi recusandae optio sint molestias laborum ex cum nemo
                voluptates eos ut assumenda. Repellat temporibus omnis
                consequuntur ipsa aut hic, libero sed sequi animi perferendis
                fugit maiores velit accusantium! Ipsam expedita nam perferendis
                in a? Eos inventore expedita architecto impedit eligendi.
              </p>
            </div>
            <div className=" col-span-5">
              <div>
                <div>
                  <p className="text-justify font-semibold">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Maiores eveniet asperiores molestiae, aliquid explicabo
                    consequuntur totam tempora perspiciatis minus quibusdam,
                    commodi harum voluptatum eum tempore illo praesentium?
                    Aliquid
                  </p>
                </div>
                <div className="flex justify-between mt-5">
                  <Image
                    src={"/assets/images/Image05.png"}
                    alt="Image05"
                    width={180}
                    height={180}
                  />
                  <p className="text-justify ml-3 w-[420px] font-semibold">
                    Lorem ippisicing elit. Maiores eveniet asperiores molestiae,
                    aliquid explicabo consequuntur totam tempora perspiciatis
                    minus quibusdam, commodi harum voluptatum eum tempore ilsum
                    dolor sit amet consectetur adilo praesentium? Aliquid
                    Maiores eveniet asperiores molestiae, aliquid explicabo
                    consequuntur totam tempora perspiciatis consequuntur totam
                    tempora perspiciatis
                  </p>
                </div>
                <div className="flex justify-between mt-5">
                  <Image
                    src={"/assets/images/Image01.png"}
                    alt="Image05"
                    width={180}
                    height={180}
                  />
                  <p className="text-justify ml-3 w-[420px] font-semibold">
                    Lorem ippisicing elit. Maiores eveniet asperiores molestiae,
                    aliquid explicabo consequuntur totam tempora perspiciatis
                    minus quibusdam, commodi harum voluptatum eum tempore ilsum
                    dolor sit amet consectetur adilo praesentium? Aliquid
                    Maiores eveniet asperiores molestiae, aliquid explicabo
                    consequuntur totam tempora perspiciatis consequuntur totam
                    tempora perspiciatis
                  </p>
                </div>
                <div>
                  <p className="text-justify mt-2 font-semibold">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Maiores eveniet asperiores molestiae, aliquid explicabo
                    consequuntur totam tempora perspiciatis minus quibusdam,
                    commodi harum voluptatum eum tempore illo praesentium?
                    <br /> Aliquid Lorem ipsum dolor sit amet consectetur
                    adipisicing elit. Cupiditate, a facere non ipsum delectus
                    ea. At earum magni rem minima consequuntur vitae voluptatum
                    in? Porro
                    <br /> delectus, tenetur nulla explicabo doloribus
                    voluptatibus id officiis suscipit{" "}
                  </p>
                </div>
              </div>
            </div>
          </div> */}
          <div className="p-1">
            <div>
              <p className="text-justify font-semibold">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio
                corporis, laborum aliquam magni earum libero nesciunt fugit
                excepturi! Iusto dolor vitae sint commodi quibusdam nemo
                explicabo. Repellat ab praesentium quam minima quia illum id
                exercitationem reprehenderit minus, accusamus iste! Quia dolor,
                molestiae ducimus sapiente quos pariatur in labore obcaecati
                maiores?
              </p>
            </div>
            <div className="grid grid-cols-3 gap-2 pt-1 h-[350px] items-center">
              <div className="">
                <Image
                  src={"/assets/images/Image04.png"}
                  alt="Image04"
                  width={180}
                  height={200}
                />
              </div>
              <div className="">
                <Image
                className="pb-2"
                  src={"/assets/images/Image03.png"}
                  alt="Image04"
                  width={180}
                  height={200}
                />
                <Image
                  src={"/assets/images/Image02.png"}
                  alt="Image04"
                  width={180}
                  height={200}
                />
              </div>
              <div className="flex items-end justify-end mx-auto h-full">
              <div className="">
                <Image
                className="pb-2"
                  src={"/assets/images/Image05.png"}
                  alt="Image04"
                  width={180}
                  height={200}
                />
                <Image
                  src={"/assets/images/Image01.png"}
                  alt="Image04"
                  width={180}
                  height={200}
                />
              </div>
              </div>
            </div>
            <div className="pt-5">
              <p className="text-justify font-semibold">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim maiores molestias consectetur delectus deleniti veritatis et, quisquam animi odit? Fugit nisi, modi praesentium corporis et nam esse repellat sed, perferendis ipsam possimus corrupti alias delectus dolorem, quidem dolor quasi cupiditate voluptates. Placeat consectetur incidunt, consequatur totam quisquam itaque nostrum alias qui. Perspiciatis, voluptas modi architecto maiores ab eos cupiditate, quidem distinctio exercitationem reiciendis quis repudiandae assumenda consectetur eaque, quas necessitatibus?
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
