import { Inter } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import ProductCard from "../components/Product/productCard";
import DetailsCard from '../components/Product/detailsCard';
import SliderCard from '../components/Product/sliderProduct'


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [pokemonList, setpokemonList] = useState<any>([])

  const gqlQuery = `query pokemons($limit: Int, $offset: Int) {
    pokemons(limit: $limit, offset: $offset) {
      results {
        url
        name
        image
      },
    }
  }`;
  
  const gqlVariables = {
    limit: 10,
    offset: 1,
  };
   useEffect(() => {
     const res = async ()=>{
        try {
          const res = await fetch('https://graphql-pokeapi.graphcdn.app/', {
            credentials: 'omit',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              query: gqlQuery,
              variables: gqlVariables,
            }),
            method: 'POST',
          }).then((res) => res.json())
          setpokemonList(res?.data?.pokemons?.results)
        } catch (error) {
          
        }
     }
      res()
   }, [])

   
  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.main1}>
          <div className="flex justify-center mb-5">
            <Image
              src={"/assets/images/Logo.png"}
              alt="logo"
              width={200}
              height={200}
            />
          </div>
          <div className={styles.productView}>
            <ProductCard arr={pokemonList}/>
          </div>


          <div className={styles.sliderView}>
            <SliderCard arr={pokemonList}/>
          </div>
        </div>
      </div>
      <DetailsCard/>
    </>
  );
}
